name: Build KeyballBLE

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      config: config
      boards: >
        seeeduino_xiao_ble
      shields: >
        KeyballBLE_L
        KeyballBLE_R
        settings_reset
